#! /bin/bash
alias cdj='cd "$JSHOR"'
alias go='bash "$JSHOR/scripts/go.sh"'
alias gimme='bash "$JSHOR/scripts/gimme.sh"'
alias dag='bash "$JSHOR/scripts/dag.sh"'
alias jira='bash "$JSHOR/scripts/open_jira.sh"'
alias conf='bash "$JSHOR/scripts/open_conf.sh"'
alias peek='bash "$JSHOR/scripts/peek.sh"'
alias ala='sudo bash "$JSHOR/scripts/alias_adder.sh"'
alias addkeys='bash "$JSHOR/scripts/add_keys.sh"'
alias gmd='bash "$JSHOR/scripts/candi_meter_query.sh"'
